{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rag-platform.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "rag-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
{{ include "rag-platform.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.ingressNamespaceLabels | nindent 14 }}
          podSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.ingressPodLabels | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8501
    - from:
        - namespaceSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.monitoringNamespaceLabels | nindent 14 }}
          podSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.monitoringPodLabels | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8501
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.dnsNamespaceLabels | nindent 14 }}
          podSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.dnsPodLabels | nindent 14 }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.ollamaPodLabels | nindent 14 }}
      ports:
        - protocol: TCP
          port: 11434
{{- end }}
