{{- if .Values.serviceAccount.create }}
{{- $annotations := deepCopy .Values.serviceAccount.annotations }}
{{- if and .Values.vaultIntegration.enabled .Values.vaultIntegration.authentication.enabled }}
{{- $annotations = mergeOverwrite $annotations .Values.vaultIntegration.authentication.serviceAccountAnnotations }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ollama.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ollama.labels" . | nindent 4 }}
{{- with $annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
automountServiceAccountToken: false
{{- end }}
