apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ollama.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "ollama.selectorLabels" . | nindent 4 }}
  ports:
    - { name: http, protocol: TCP, port: {{ .Values.service.port }}, targetPort: http }
